flip_idx: [25, 24, 27, 26, 20, 21, 22, 23, 16, 17, 18, 19, 28, 29, 14, 15, 8, 9, 10,
  11, 4, 5, 6, 7, 1, 0, 3, 2, 12, 13, 31, 30, 33, 32, 35, 34, 37, 36, 39, 38, 40,
  41, 42, 50, 51, 52, 53, 54, 55, 56, 43, 44, 45, 46, 47, 48, 49]
kpt_shape: [57, 3]
path: .
train: /Users/weihern/Documents/Sports Analytics/Eagle/eagle/models/weights/datasets/images/train
val: /Users/weihern/Documents/Sports Analytics/Eagle/eagle/models/weights/datasets/images/test
names:
  0: pitch
